name: ventroar_app
description: A new Flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #flutter官方推荐的状态管理插件
  provider: ^6.0.3
  #getwidgeUI组件库
  getwidget: ^3.0.1
  #http请求库
  dio: ^4.0.6
  #toast组件库
  fluttertoast: ^8.0.7
  #底部导航栏组件
  curved_navigation_bar: ^1.0.1
  #页面切换组件 (建议) 代码使用: LiquidSwipe(pages:scaffolds)
  #liquid_swipe: ^2.1.0
  #徽标
  badges: ^2.0.2
  #font_awesome图标库
  font_awesome_flutter: ^10.1.0
  #字体动画库
  animated_text_kit: ^4.2.1
  #item滑动抽屉组件
  flutter_slidable: ^1.2.0
  #动画组件包
  animations: ^2.0.2
  #谷歌字体包
  google_fonts: ^3.0.0
  #谷歌动态导航栏
  google_nav_bar: ^5.0.6
  #状态数据储存包 本项目用来存储一些主题状态信息
  shared_preferences: ^2.0.15
  #具有一组内置效果的可定制动画页面指示器。
  smooth_page_indicator: ^1.0.0+2
  #加载动画组件包
  loading_animation_widget: ^1.2.0+1
  #grouped布局组件
  grouped_list: ^4.2.0
  #聊天气泡组件
  chat_bubbles: ^1.2.0
  #本地数据存储sqflite插件
  sqflite: ^2.0.2+1
  #一个全面的、跨平台的 Dart 路径操作库。
  path: ^1.8.0
  #rive动画插件
  rive: ^0.9.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  assets:
    - static/
    - static/img/
    - static/animations/dark/
    - static/animations/light/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.ventroar_app
    iosBundleIdentifier: com.example.ventroarApp
